LineLength:
  Max: 80
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"  # Arrays use brackets

SpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting

RegexpLiteral:
  Enabled: false

inherit_from: test/support/rubocop/enabled.yml
inherit_from: test/support/rubocop/disabled.yml
